version: '3.7'
services:

    nginx:
        container_name: todo-nginx-container

        image: todo-nginx-image

        build:
            context: ../
            dockerfile: docker/nginx/Dockerfile

        ports:
            - "8081:80"
        volumes:
          - type: bind
            source: "${APP_PATH}/laravel"
            target: /var/www/html/phpapp

        depends_on:
            - php

    php:
        container_name: todo-php-container
        image: todo-php-image

        build:
            context: ../
            dockerfile: docker/php/Dockerfile

        volumes:
            - type: bind
              source: "${APP_PATH}/laravel"
              target: /var/www/html/phpapp

        depends_on:
            - mysql

    mysql:
        container_name: todo-mysql-container
        image: mysql:8

        environment:
            MYSQL_ROOT_PASSWORD: "todo"
            MYSQL_DATABASE: "${DB_DATABASE}"
            MYSQL_USER: "${DB_USERNAME}"
            MYSQL_PASSWORD: "${DB_PASSWORD}"

        ports:
            - "33306:3306"
